### ISSUE TITLE
Make the search results show only eligible donors

### ISSUE THREAD

**Issue by modasserbillah** [sh4hids/brf-client#3]
The search UI shows all donors in the database, we need to show only the eligible donors. List of eligible donors are exposed at `/eligible_donors` in the backend. Use that endpoint to fetch search results.

**Comment by sh4hids** [comment]
@modasserbillah I changed the API URL in this commit: https://github.com/sh4hids/brf-client/commit/cd1c916b341364f7e847af38acb9004f6107f7f4 . But the filter is not working. I tested on admin panel, same issue.

**Comment by modasserbillah** [comment]
I have fixed the issue, will push shortly to server. Please update the url for filters like this: 
```
api/v1/persons/eligible-donors/?name__icontains=&mobile__icontains=&date_of_birth=&address=&blood_group=&role=&gender=&last_donated_on=&last_received_on=&emergency_contact_name=&emergency_contact_phone=&community=&place=
```
Include search params after each `=`

Also, the url is changed to `eligible-donors` from `eligible_donors`.

**Comment by modasserbillah** [comment]
Pushed to heroku

**Comment by sh4hids** [comment]
Fixed on https://github.com/sh4hids/brf-client/commit/76138f2790952b9e4a75114738e01c295fe11f67
